package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

public class Messages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.messages.id
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.messages.text
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.messages.jsonb_value
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    private Object jsonbValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.messages.id
     *
     * @return the value of public.messages.id
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.messages.id
     *
     * @param id the value for public.messages.id
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.messages.text
     *
     * @return the value of public.messages.text
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.messages.text
     *
     * @param text the value for public.messages.text
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.messages.jsonb_value
     *
     * @return the value of public.messages.jsonb_value
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public Object getJsonbValue() {
        return jsonbValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.messages.jsonb_value
     *
     * @param jsonbValue the value for public.messages.jsonb_value
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public void setJsonbValue(Object jsonbValue) {
        this.jsonbValue = jsonbValue;
    }
}