package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.order_detail_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private String orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.quantity
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.unit_price
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private Integer unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.product_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_details.order_detail_id
     *
     * @return the value of public.order_details.order_detail_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_details.order_detail_id
     *
     * @param orderDetailId the value for public.order_details.order_detail_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_details.quantity
     *
     * @return the value of public.order_details.quantity
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_details.quantity
     *
     * @param quantity the value for public.order_details.quantity
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_details.unit_price
     *
     * @return the value of public.order_details.unit_price
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_details.unit_price
     *
     * @param unitPrice the value for public.order_details.unit_price
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_details.product_id
     *
     * @return the value of public.order_details.product_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_details.product_id
     *
     * @param productId the value for public.order_details.product_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}