package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

public class OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_number
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_detail_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private String orderDetailId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.order_number
     *
     * @return the value of public.orders.order_number
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.order_number
     *
     * @param orderNumber the value for public.orders.order_number
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.order_detail_id
     *
     * @return the value of public.orders.order_detail_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.order_detail_id
     *
     * @param orderDetailId the value for public.orders.order_detail_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
}