package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.order_detail_id
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.quantity
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.unit_price
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private Integer unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_details.product_id
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String productId;
}