package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_number
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_detail_id
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String orderDetailId;
}