package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.product_id
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.product_name
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String productName;
}