package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.product_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.product_name
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    private String productName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.products.product_id
     *
     * @return the value of public.products.product_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.products.product_id
     *
     * @param productId the value for public.products.product_id
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.products.product_name
     *
     * @return the value of public.products.product_name
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.products.product_name
     *
     * @param productName the value for public.products.product_name
     *
     * @mbg.generated Wed May 13 23:10:08 JST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }
}