package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.name
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.id
     *
     * @return the value of public.users.id
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.id
     *
     * @param id the value for public.users.id
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.name
     *
     * @return the value of public.users.name
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.name
     *
     * @param name the value for public.users.name
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}