package com.jigowatts.springboot_with_mybatis.infrastructure.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.name
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    private String name;
}