package com.jigowatts.springboot_with_mybatis.infrastructure.mapper;

import com.jigowatts.springboot_with_mybatis.infrastructure.entity.Messages;
import com.jigowatts.springboot_with_mybatis.infrastructure.entity.MessagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    long countByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int deleteByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int insert(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int insertSelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    List<Messages> selectByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    Messages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int updateByExampleSelective(@Param("record") Messages record, @Param("example") MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int updateByExample(@Param("record") Messages record, @Param("example") MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int updateByPrimaryKeySelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbg.generated Tue May 12 23:58:07 JST 2020
     */
    int updateByPrimaryKey(Messages record);
}