package com.jigowatts.springboot_with_mybatis.infrastructure.mapper;

import com.jigowatts.springboot_with_mybatis.infrastructure.entity.OrdersExample;
import com.jigowatts.springboot_with_mybatis.infrastructure.entity.OrdersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int deleteByPrimaryKey(OrdersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int insert(OrdersKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int insertSelective(OrdersKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    List<OrdersKey> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByExampleSelective(@Param("record") OrdersKey record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.orders
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByExample(@Param("record") OrdersKey record, @Param("example") OrdersExample example);
}