package com.jigowatts.springboot_with_mybatis.infrastructure.mapper;

import com.jigowatts.springboot_with_mybatis.infrastructure.entity.OrderDetails;
import com.jigowatts.springboot_with_mybatis.infrastructure.entity.OrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    long countByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int deleteByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int deleteByPrimaryKey(String orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    List<OrderDetails> selectByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    OrderDetails selectByPrimaryKey(String orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByExampleSelective(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByExample(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_details
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByPrimaryKey(OrderDetails record);
}