package com.jigowatts.springboot_with_mybatis.infrastructure.mapper;

import com.jigowatts.springboot_with_mybatis.infrastructure.entity.Products;
import com.jigowatts.springboot_with_mybatis.infrastructure.entity.ProductsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    long countByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int deleteByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int insert(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int insertSelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    List<Products> selectByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    Products selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByExampleSelective(@Param("record") Products record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByExample(@Param("record") Products record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByPrimaryKeySelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated Sat May 16 13:04:10 JST 2020
     */
    int updateByPrimaryKey(Products record);
}